### PR TITLE
use version number instead of release in .travis.yml

### PR DESCRIPTION
**Pull request by tkelman**
release will change over time, but your REQUIRE file says this package supports julia 0.5 so it should continue to be tested

### CODE REVIEW

**Comment by vonDonnerstein** [comment]
That's a valid point. I guess .travis.yml and REQUIRE really should be consistent. I think I would prefer the other way around, however. My take was always that QuantumLab should only support the current stable julia release at any point in time. So I definitely want travis to fail when a new julia version is released but the codebase of QuantumLab has not yet been updated, but not when an older version is no longer supported.

Is there a way to REQUIRE the most current version of julia?

**Comment by tkelman** [comment]
No, REQUIRE only supports version numbers. You can manually change REQUIRE when there's a new release, it's not like they're that frequent.

**Comment by vonDonnerstein** [comment]
Ok, great. Thanks for clarifying. In that case, we should probably check for the version specified in REQUIRE (which can be manually updated when new versions are released) and additionally keep checking for the "release" version - despite the redundancy - to make sure to capture the failing state between the release of a new julia version and the corresponding update of the QuantumLab code. @tkelman Would you have a different suggestion?

Btw, I've just pushed the updated code for julia v0.6 and have updated the .travis.yml and REQUIRE files accordingly (I added comments in both files least I forget to keep them updated in the future).

**Comment by tkelman** [comment]
Nightly would capture that during the rc period, before "release" is actually doing anything useful. Support for "release" may be removed from Travis' `language: julia` code.

**Comment by vonDonnerstein** [comment]
Closing this, since these things are now done in `Project.toml` instead of `REQUIRE` anyway.

I've set the required julia version to "1", which should always be the most up-to-date julia version (at least until julia v2.0.0)

**Pull request closed without merging**
