### PR TITLE
Make it run Julia 0.5

### PR DESCRIPTION
**Pull request by jiahao**
I found out about this package at the Julia Manchester workshop today. Very interesting :)

Here is a PR to make the code run on Julia 0.5, which was released officially today.

It almost works, but not quite. the `Documenter` module is broken because `Base.doc!` changed and I don't really understand enough about what your module is supposed to be doing in order to understand what needs to be changed.

Also normalize whitespace: expand tabs, strip DOS ^M junk

### CODE REVIEW

**Comment by vonDonnerstein** [comment]
Very cool! Thank you for your efforts. I'll be back from a conference I'm attending by Friday next week. Then I'll try to fix the last bits up asap. The results of the test run make it seem to me like there is something we rely on in TensorOperations.jl which also still needs to be updated to j0.5. So maybe it will need a few days but I'm going to pull as soon as I can.

**Comment by jiahao** [comment]
TensorOperations.jl is fixed on master and perhaps we can ask @Jutho to tag a new version

**Comment by Jutho** [comment]
There are actually a few bugs that need to be fixed/updated for 0.5 as soon as you use TensorOperations.jl in conjunction with `SubArray`s. I'll try to fix asap (and then tag a new version) but this week will be very busy for me. I hope to find some time next week.

**Comment by Jutho** [comment]
I did actually tag a new version yesterday (since I also needed it myself :-) )

**Comment by vonDonnerstein** [comment]
Alright, I finally found the time to correct the DocumentationModule stuff for j0.5 and merge your commit, @jiahao. Thank you very much again. Also thanks to @Jutho for your work on TensorOperations.jl. It all seems to run through now. (Just that TravisCI still sees j0.4.7 as latest release, but that will probably get solved with time.)

**Pull request merged**
