### PR TITLE
Use dirname(@__FILE__) instead of Pkg.dir

### PR DESCRIPTION
**Pull request by tkelman**
This allows installing the package elsewhere.

Add testing against 0.5 to Travis - this runs the most
recent RC now, release once final tags are done

### CODE REVIEW

**Comment by vonDonnerstein** [comment]
@tkelman, thank you for your input. Very much appreciated! Our code is trimmed against the latest stable of julia (0.4 at the moment). I'm aiming for 0.5 compatibility by the time it reaches stable status. Until I have rewritten the code in that way there seems to be no point in testing against 0.5 as those tests are bound to fail. So I'm only merging in the main change (@**FILE** instead of Pkg.dir).

**Comment by tkelman** [comment]
You can set it as an allowed_failure on Travis until then, so it runs but won't make your status red

**Comment by tkelman** [comment]
also note that "release" will change to 0.5 soon, so it's better to list 0.4 as a specific version number

**Comment by vonDonnerstein** [comment]
That's cool! I didn't know that was possible. Thanks for letting me know. I have just committed your suggestions in 7e50da4.

**Pull request merged**
